name = "AgoraPhysics"
version = "0.1.0"
defaultTargets = ["agoraphysics"]

[[lean_lib]]
name = "AgoraPhysics"

[[lean_exe]]
name = "agoraphysics"
root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
